#!/bin/bash
#################################
## adroit-developers-stuttgart ##
##                             ##
#################################

CMDF=`basename $0`
while getopts u:p:d:o: option
do
        case "${option}"
        in
                u) USER=${OPTARG};;
                p) PASS=${OPTARG};;
                d) DB=${OPTARG};;
                o) OUT=${OPTARG};;
	esac
done

if [ "x$1" == "x" ]; then
  echo "Usage: $CMDF -u <USER> -p <PASS> -d <DATABASE> -o <OUTFILE>"
  exit
fi

echo "Starting MySQL dump..."

mysqldump -u$USER -p$PASS --compatible=ansi --skip-opt $DB > $OUT.sql

cat $OUT.sql |
grep -v ' KEY "' |
grep -v ' UNIQUE KEY "' |
grep -v ' PRIMARY KEY ' |
sed '/^SET/d' |
sed 's/ unsigned / /gI' |
sed 's/ auto_increment/ primary key autoincrement/gI' |
sed 's/ smallint([0-9]*) / integer /gI' |
sed 's/ tinyint([0-9]*) / integer /gI' |
sed 's/ int([0-9]*) / integer /gI' |
sed 's/ CHARACTER SET [^ ,]*/ /gI ' |
sed 's/ enum([^)]*) / varchar(255) /gI' |
sed 's/ on update [^,]*//gI' |
sed 's/\\r\\n/\\n/gI' |
sed 's/\\"/"/gI' |
sed 's/DELIMITER ;;//gI' |
sed 's/DELIMITER ;//gI' |
perl -e 'local $/;$_=<>;s/,\n\)/\n\)/gs;print "begin;\n";print;print "commit;\n"' |
perl -pe '
if (/^(INSERT.+?)\(/) {
  $a=export;
  s/\\'\''/'\'\''/g;
  s/\\n/\n/g;
  s/\),\(/\);\n$a\(/g;
}
' > $OUT.fix.sql

echo SQL file created. Now beginning to create sqlite3 DB.
rm -f $OUT
cat $OUT.fix.sql | sqlite3 $OUT > $OUT.export.out 2> $OUT.export.err

ERRORS=`cat $OUT.export.err | wc -l`
if [ $ERRORS == 0 ]; then
  cat $OUT.export.err
  echo "Conversion completed without error. Output file: $OUT"
  rm $OUT.sql
  rm $OUT.fix.sql
  rm $OUT.export.out
  rm $OUT.export.err
else
  echo "There were errors during conversion.  Please review $OUT.export.out, $OUT.export.err, $OUT.sql and $OUT.fix.sql for details."
fi

